openapi: 3.0.3
info:
  title: Foo API
  description: Foo API
  version: 1.0.0

paths:
  /foo:
    get:
      tags:
        - Foo
      operationId: getFoo
      responses:
        200:
          description: Returns foo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"

components:
  schemas:
    Foo:
      type: object
      properties:
        id:
          type: integer
        type:
          $ref: "#/components/schemas/FooType"
    FooType:
      type: string
      enum:
        - 1
        - 2